<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class StaffDirectorySeeder extends Seeder
{
    /**
     * Imports the real VIMS Hospitals staff directory (source: "Mail ID List For VSuite_29.07.26.xlsx").
     * Everyone lands with role HOD and username == name, except entries that set their own 'role'
     * (Dr.KMS / Medical Director and Mr.Venkatesh.K.K / General Manager are SuperAdmin — they anchor
     * the Clinical/Non Clinical approval chains in ApprovalPathResolver, which routes by exact
     * department name, so Venkatesh's department is set to 'General Manager' rather than 'Operations').
     * Default password for every imported account is 'password' and should be rotated on first login.
     */
    public function run(): void
    {
        $staff = [
            [
                'name' => 'Dr.KMS',
                'emp_id' => '3006',
                'designation' => 'Medical Director',
                'department' => 'Medical Director',
                'division' => 'Clinical',
                'email' => 'md@vimshospitals.com',
                'phone' => '9362128563',
                'role' => 'SuperAdmin',
            ],
            [
                'name' => 'Mr.Venkatesh.K.K',
                'emp_id' => '4093',
                'designation' => 'Deputy COO',
                'department' => 'General Manager',
                'division' => 'Non Clinical',
                'email' => 'gmoperations@vimshospitals.com',
                'phone' => '9047783335',
                'role' => 'SuperAdmin',
            ],
            [
                'name' => 'Dr.Ashok',
                'emp_id' => '3114',
                'designation' => 'DMD',
                'department' => 'Emergency',
                'division' => 'Clinical',
                'email' => 'drashok@vimshospitals.com',
                'phone' => '9751143331',
            ],
            [
                'name' => 'Mr.Aneesh.K.V',
                'emp_id' => '4485',
                'designation' => 'Quality Head',
                'department' => 'Quality',
                'division' => 'Non Clinical',
                'email' => 'qualityhead@vimshospitals.com',
                'phone' => '8606296075',
            ],
            [
                'name' => 'Dr.Vijay',
                'emp_id' => '4424',
                'designation' => 'Asst.Manager Quality',
                'department' => 'Quality',
                'division' => 'Non Clinical',
                'email' => 'quality@vimshospitals.com',
                'phone' => '9500650343',
            ],
            [
                'name' => 'Mr.Ganesan.P',
                'emp_id' => '311',
                'designation' => 'PRO',
                'department' => 'PRO',
                'division' => 'Non Clinical',
                'email' => 'pro@vimshospitals.com',
                'phone' => '7094450096',
            ],
            [
                'name' => 'Mr.Sathiyaseelan.N',
                'emp_id' => '4188',
                'designation' => 'Billing Manager',
                'department' => 'Billing',
                'division' => 'Non Clinical',
                'email' => 'billingmanager@vimshospitals.com',
                'phone' => '9363643934',
            ],
            [
                'name' => 'Mr.Soundarajan.M',
                'emp_id' => '1881',
                'designation' => 'Assistant Manager Billing',
                'department' => 'Billing',
                'division' => 'Non Clinical',
                'email' => 'billing@vinayakahospital.com',
                'phone' => '7904155056',
            ],
            [
                'name' => 'Mr.Karthick.M',
                'emp_id' => '1973',
                'designation' => 'Assistant Manager',
                'department' => 'Biomedical',
                'division' => 'Non Clinical',
                'email' => 'karthick@vimshospitals.com',
                'phone' => '9791849566',
            ],
            [
                'name' => 'Ms.Kalaiyarasi.S',
                'emp_id' => '915',
                'designation' => 'Senior Technician',
                'department' => 'Blood Bank',
                'division' => 'Clinical',
                'email' => 'bloodbank@vimshospitals.com',
                'phone' => '6379179723',
            ],
            [
                'name' => 'Mr.Parmeshwaran',
                'emp_id' => '2332',
                'designation' => null,
                'department' => 'Branding',
                'division' => 'Non Clinical',
                'email' => 'branding@vimshospitals.com',
                'phone' => '6384440067',
            ],
            [
                'name' => 'Ms.Divya.R.P',
                'emp_id' => '4163',
                'designation' => 'Pharmacologist',
                'department' => 'Clinical Pharmacology',
                'division' => 'Clinical',
                'email' => 'clinicalpharmacology@vimshospitals.com',
                'phone' => '8903902121',
            ],
            [
                'name' => 'Mr.Shankar.G',
                'emp_id' => '1379',
                'designation' => 'Incharge',
                'department' => 'Dialysis',
                'division' => 'Clinical',
                'email' => 'dialysis@vimshospitals.com',
                'phone' => '9003859245',
            ],
            [
                'name' => 'Ms.Jothimani',
                'emp_id' => '2173',
                'designation' => 'Dietician',
                'department' => 'Dietary',
                'division' => 'Non Clinical',
                'email' => 'dietary@vimshospitals.com',
                'phone' => '7094461902',
            ],
            [
                'name' => 'Mr.Sathasivam.K',
                'emp_id' => '6000',
                'designation' => 'Facility Manager',
                'department' => 'Facility',
                'division' => 'Non Clinical',
                'email' => 'k.sathasivam@vimshospitals.com',
                'phone' => '8248050905',
            ],
            [
                'name' => 'Mr.Saravanan.T',
                'emp_id' => '1656',
                'designation' => 'Finance Head',
                'department' => 'Finance',
                'division' => 'Non Clinical',
                'email' => 'saravanan.t@vinayakahospital.com',
                'phone' => '9952421709',
            ],
            [
                'name' => 'Mr.Sakthivel',
                'emp_id' => null,
                'designation' => 'Asst.Manager Finance',
                'department' => 'Finance',
                'division' => 'Non Clinical',
                'email' => 'finance@vinayakahospital.com',
                'phone' => '7094450102',
            ],
            [
                'name' => 'Mrs.Geetharani.S',
                'emp_id' => '4478',
                'designation' => 'GR',
                'department' => 'Guest Relation',
                'division' => 'Non Clinical',
                'email' => 'gr@vimshospitals.com',
                'phone' => '9943296754',
            ],
            [
                'name' => 'Mr.Viji.P',
                'emp_id' => '4104',
                'designation' => 'Assistant Manager',
                'department' => 'House Keeping',
                'division' => 'Non Clinical',
                'email' => 'hk@vinayakahospital.com',
                'phone' => '9894574529',
            ],
            [
                'name' => 'Ms.kalarani.G',
                'emp_id' => '2776',
                'designation' => 'Head HR',
                'department' => 'HRD',
                'division' => 'Non Clinical',
                'email' => 'headhr@vinayakahospital.com',
                'phone' => '8056369462',
            ],
            [
                'name' => 'Mr.UmaDinesh',
                'emp_id' => '4477',
                'designation' => 'HR Manager',
                'department' => 'HRD',
                'division' => 'Non Clinical',
                'email' => 'hrmanager@vimshospitals.com',
                'phone' => '8220045006',
            ],
            [
                'name' => 'Dr.Kavitha.A',
                'emp_id' => '3133',
                'designation' => 'HOD',
                'department' => 'Hospital Infection Control',
                'division' => 'Clinical',
                'email' => 'labhod@vinayakahospital.com',
                'phone' => '9443977563',
            ],
            [
                'name' => 'Mrs.Jeya Suriya',
                'emp_id' => '4171',
                'designation' => 'Audit Operations',
                'department' => 'Audit',
                'division' => 'Non Clinical',
                'email' => 'auditoperations@vinayakahospital.com',
                'phone' => '9003514397',
            ],
            [
                'name' => 'Mr.Moorthy',
                'emp_id' => '4192',
                'designation' => 'Internal Auditor',
                'department' => 'Audit',
                'division' => 'Non Clinical',
                'email' => 'internalauditor@vinayakahospital.com',
                'phone' => '8754892435',
            ],
            [
                'name' => 'Ms.Anupriya.V',
                'emp_id' => '2059',
                'designation' => 'Assistant Manager',
                'department' => 'IP Manager',
                'division' => 'Non Clinical',
                'email' => 'ipmanager@vimshospitals.com',
                'phone' => '9884427473',
            ],
            [
                'name' => 'Mr.Sampathkumar.G',
                'emp_id' => '420',
                'designation' => 'Manager',
                'department' => 'IT',
                'division' => 'Non Clinical',
                'email' => 'it@vinayakahospital.com',
                'phone' => '9788961127',
            ],
            [
                'name' => 'Mr.Mani Jasfer',
                'emp_id' => '4181',
                'designation' => 'Application Support Engineer',
                'department' => 'HIMS',
                'division' => 'Non Clinical',
                'email' => 'it.hims@vimshospitals.com',
                'phone' => '7639263939',
            ],
            [
                'name' => 'Mr.Boobalan',
                'emp_id' => null,
                'designation' => 'Application Support Engineer',
                'department' => 'HIMS',
                'division' => 'Non Clinical',
                'email' => 'hims.support@vinayakahospital.com',
                'phone' => '9698831511',
            ],
            [
                'name' => 'Mr.Chinnathambi',
                'emp_id' => '3133',
                'designation' => 'Lab Incharge',
                'department' => 'Lab',
                'division' => 'Clinical',
                'email' => 'lab@vinayakahospital.com',
                'phone' => '9443977563',
            ],
            [
                'name' => 'Mr.Dhamodharan',
                'emp_id' => '2798',
                'designation' => 'Assistant Manager',
                'department' => 'Maintenance',
                'division' => 'Non Clinical',
                'email' => 'dhamodharan@vimshospitals.com',
                'phone' => '9940991236',
            ],
            [
                'name' => 'Mr.Arulmani',
                'emp_id' => '1691',
                'designation' => 'Marketing Manager',
                'department' => 'Marketing',
                'division' => 'Non Clinical',
                'email' => 'marketing@vinayakahospital.com',
                'phone' => '9360308910',
            ],
            [
                'name' => 'Mrs.Yasodha.L',
                'emp_id' => '9427',
                'designation' => 'Senior Executive',
                'department' => 'Marketing',
                'division' => 'Non Clinical',
                'email' => 'internalmarketing@vinayakahospital.com',
                'phone' => '7094461905',
            ],
            [
                'name' => 'Mr.Ranjithkumar.J',
                'emp_id' => '4258',
                'designation' => 'Assistant Manager',
                'department' => 'Medical Record',
                'division' => 'Non Clinical',
                'email' => 'mrd@vinayakahospital.com',
                'phone' => null,
            ],
            [
                'name' => 'Mrs.Neelaveni',
                'emp_id' => '4457',
                'designation' => 'Nursing Superintendent',
                'department' => 'Nursing',
                'division' => 'Clinical',
                'email' => 'ns@vimshospitals.com',
                'phone' => '9538257801',
            ],
            [
                'name' => 'Ms.Kalaiselvi.S',
                'emp_id' => '2201',
                'designation' => 'Deputy Nursing Superintendent',
                'department' => 'Nursing',
                'division' => 'Clinical',
                'email' => 'dns@vimshospitals.com',
                'phone' => '9159999527',
            ],
            [
                'name' => 'Ms.Sri Swedha.B',
                'emp_id' => '4227',
                'designation' => 'Assistant Manager',
                'department' => 'Front Office',
                'division' => 'Non Clinical',
                'email' => 'opmanager@vimshospitals.com',
                'phone' => '8825719850',
            ],
            [
                'name' => 'Dr.Velmurugan',
                'emp_id' => '4398',
                'designation' => 'Dupty Manager Operations',
                'department' => 'Operations',
                'division' => 'Non Clinical',
                'email' => 'operations@vimshospitals.com',
                'phone' => null,
            ],
            [
                'name' => 'Ms.Latha.S',
                'emp_id' => '2685',
                'designation' => 'Assistant Manager',
                'department' => 'OT',
                'division' => 'Clinical',
                'email' => 'ot@vinayakahospital.com',
                'phone' => '9944406673',
            ],
            [
                'name' => 'Kamalakannan.D',
                'emp_id' => '4233',
                'designation' => 'Assistant Manager',
                'department' => 'Pharmacy',
                'division' => 'Clinical',
                'email' => 'pharmacy@vinayakahospital.com',
                'phone' => '9751112526',
            ],
            [
                'name' => 'Mr.Santhosh.M',
                'emp_id' => '2435',
                'designation' => 'Manager',
                'department' => 'Physiotherapy',
                'division' => 'Clinical',
                'email' => 'physio@vimshospitals.com',
                'phone' => '9843031885',
            ],
            [
                'name' => 'Mr.Santhosh Walter',
                'emp_id' => '2435',
                'designation' => 'Purchase Manager',
                'department' => 'Purchase',
                'division' => 'Non Clinical',
                'email' => 'purchasemanager@vimshospitals.com',
                'phone' => '9944146416',
            ],
            [
                'name' => 'Mr.Ragavendran',
                'emp_id' => '2185',
                'designation' => 'Assistant Manager Purchase',
                'department' => 'Purchase',
                'division' => 'Non Clinical',
                'email' => 'purchase@vinayakahospital.com',
                'phone' => '9445570915',
            ],
            [
                'name' => 'Mr.Jayavelu.J',
                'emp_id' => '924',
                'designation' => 'Senior Radiographer',
                'department' => 'Radiology',
                'division' => 'Clinical',
                'email' => 'radiology@vimshospitals.com',
                'phone' => '7010277313',
            ],
            [
                'name' => 'Mr.Mohammed Hasim.S',
                'emp_id' => '4397',
                'designation' => 'Incharge',
                'department' => 'Stores',
                'division' => 'Non Clinical',
                'email' => 'stores@vimshospitals.com',
                'phone' => '9578808875',
            ],
            [
                'name' => 'Mr.Prabakarn M S J',
                'emp_id' => '2005',
                'designation' => 'Transplant Co-ordinator',
                'department' => 'Transplant',
                'division' => 'Clinical',
                'email' => 'vimskidneytransplant@vimshospitals.com',
                'phone' => '9791540131',
            ],
            [
                'name' => 'Mr.Venkatesh',
                'emp_id' => '9148',
                'designation' => 'Incharge',
                'department' => 'Ward - Emergency',
                'division' => 'Clinical',
                'email' => 'emergency@vimshospitals.com',
                'phone' => '9994541700',
            ],
            [
                'name' => 'Mr.Devaraj',
                'emp_id' => '1852',
                'designation' => 'Chief Security Officer',
                'department' => 'Security',
                'division' => 'Non Clinical',
                'email' => 'securityoffice@vinayakahospital.com',
                'phone' => '9788158324',
            ],
            [
                'name' => 'Mr.Mohammed Azam.H',
                'emp_id' => '603',
                'designation' => 'Assistant Manager',
                'department' => 'Transport',
                'division' => 'Non Clinical',
                'email' => 'transport@vinayakahospital.com',
                'phone' => '6384499089',
            ],
        ];

        foreach ($staff as $person) {
            User::updateOrCreate(
                ['email' => $person['email']],
                array_merge(['role' => 'HOD'], $person, [
                    'username' => $person['name'],
                    'password' => Hash::make('password'),
                    'is_active' => 1,
                    'can_use_api' => 1,
                ])
            );
        }
    }
}
